---
name: WireGuard UI
version: 1.1.127
url: https://github.com/samrocketman/addons-homeassistant/tree/main/wireguard-ui
slug: wireguard-ui
description: >-
  Web UI for provisioning and managing device keys and configurations for
  WireGuard
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
panel_icon: mdi:vpn
panel_title: WireGuard VPN
options:
  single_user_mode: true
  default_interface_addresses:
    - "10.252.1.0/24"
    - "10.252.2.0/24"
  subnet_ranges:
    - "Home: 10.252.1.0/24"
    - "DMZ Network: 10.252.2.0/24"
  dmz_subnet:
    - "10.252.2.0/24"
  dmz_subnet_allow:
    - "default_route_ip|53/udp"
# https://developers.home-assistant.io/docs/add-ons/configuration/#options--schema
schema:
  single_user_mode: bool
  default_interface_addresses:
    - "match(^([0-9]{1,3}\\.){3}[0-9]{1,3}/[1-3]?[0-9]$)?"
  clear_session_on_boot: bool?
  subnet_ranges:
    - "match(^[^:]+: ?(,?([0-9]{1,3}\\.){3}[0-9]{1,3}/[1-3]?[0-9])+$)?"
  dmz_subnet:
    - "match(^([0-9]{1,3}\\.){3}[0-9]{1,3}/[1-3]?[0-9]$)?"
  dmz_subnet_allow:
    - "match(^((((default_route_ip|([0-9]{1,3}\\.){3}[0-9]{1,3}(/[1-3]?[0-9])?)\\|?){1,2}([0-9,:]+/(tcp|udp|icmp|any))?))$)?"
  dmz_subnet_related: bool?
  isolated_subnet:
    - "match(^([0-9]{1,3}\\.){3}[0-9]{1,3}/[0-9]+$)?"
  isolated_subnet_allow:
    - "match(^((((default_route_ip|([0-9]{1,3}\\.){3}[0-9]{1,3}(/[1-3]?[0-9])?)\\|?){1,2}([0-9,:]+/(tcp|udp|icmp|any))?))$)?"
  isolated_subnet_related: bool?
  default_client_dns: str?
  default_client_endpoint: str?
  log_level: list(debug|info|warn|error|off)?
  email_from_address: str?
  email_from_name: str?
  sendgrid_api_key: password?
  smtp_hostname: "match(^([-a-zA-Z0-9.]{0,253}|[0-9a-f:.]*)$)?"
  smtp_port: int(0,65535)?
  smtp_username: str?
  smtp_password: password?
  smtp_auth_type: list(PLAIN|LOGIN|NONE)?
  smtp_encryption: list(NONE|SSL|SSLTLS|TLS|STARTTLS)?
  smtp_helo: "match(^([-a-zA-Z0-9.]{0,253}|[0-9a-f:.]*)$)?"
  telegram_token: password?
  telegram_allow_conf_request: bool?
  telegram_flood_wait: int(0,)?
ports:
  51820/udp: 51820
