---
name: Wireguard UI
version: 1.1.47
slug: wireguard-ui
description: >-
  Web UI for provisioning and managing device keys and configurations for
  Wireguard.
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
panel_icon: mdi:vpn
panel_title: WireGuard VPN
options:
  default_client_endpoint: ""
  default_client_dns: "1.1.1.1"
  single_user_mode: true
schema:
  default_client_endpoint: str
  default_client_dns: str
  single_user_mode: bool
ports:
  51820/udp: 51820
