---
name: Wireguard UI
version: 1.1.6
slug: wireguard-ui
description: >-
  Web UI for provisioning and managing device keys and configurations for
  Wireguard.
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
panel_icon: mdi:vpn
panel_title: WireGuard UI
options:
  endpoint: null
  dns: null
schema:
  endpoint: str
  dns: str
ports:
  51820/udp: 51820
ports_description:
  51820/udp: Wireguard data
