---
name: Wireguard UI
version: 1.1.112
url: https://github.com/samrocketman/addons-homeassistant/tree/main/wireguard-ui
slug: wireguard-ui
description: >-
  Web UI for provisioning and managing device keys and configurations for
  WireGuard
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
panel_icon: mdi:vpn
panel_title: WireGuard VPN
options:
  single_user_mode: true
  default_interface_addresses: "10.252.1.0/24,10.252.2.0/24"
  dmz_subnet: "10.252.2.0/24"
# https://developers.home-assistant.io/docs/add-ons/configuration/#options--schema
schema:
  single_user_mode: bool
  default_interface_addresses: "match(^([ ,/0-9.]+)?$)?"
  clear_session_on_boot: bool?
  subnet_ranges: "match(^(;? ?[^:]+:[/0-9.,]+)*$)?"
  dmz_subnet: "match(^([ /0-9.]+)?$)?"
  default_client_dns: str?
  default_client_endpoint: str?
  log_level: list(debug|info|warn|error|off)?
ports:
  51820/udp: 51820
